version: '3.9'

services:
  dbmysql:
    image: mysql
    restart: always
    volumes: 
      # prende lo script seed.sql per creare e popolare le tabelle
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 3306:3306
    env_file:
      - .env
  
  api:
    build: ./API
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - dbmysql

  websocketserver:
    build: ./Server
    restart: on-failure
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on: 
      - dbmysql

  websocketclient:
    build: ./Client
    restart: on-failure
    env_file:
      - .env 