version: '3.4'

services:
  dbmysql:
    image: mysql
    restart: always
    volumes: 
          # prende lo script seed.sql per creare e popolare le tabelle
          - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD= ""
      - MYSQL_DATABASE=project_pa
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password
  
  api:
    build: ./API
    ports:
      - 3000:3000
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD= 
      - DB_NAME=project_pa
      - DB_PORT=3306
      - SECRET_KEY=qwertyuiopasdfghjklzxcvbnm123456
    depends_on:
      - dbmysql

  websocketserver:
    build: ./Server
    ports:
      - 3001:3001
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD= 
      - DB_NAME=project_pa
      - DB_PORT=3306
      - WS_PORT=3001
      - ERROR_PERCENTAGE=15
    depends_on:
      - dbmysql

  websocketclient:
    build: ./Client
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD= 
      - DB_NAME=project_pa
      - DB_PORT=3306
      - WS_PORT=3001
      - ERROR_PERCENTAGE=15
    depends_on:
      - websocketserver
          