version: '3.9'

services:
  dbmysql:
    image: mysql
    restart: always
    volumes: 
          # prende lo script seed.sql per creare e popolare le tabelle
          - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=project_pa
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password
  
  api:
    build: ./API
    ports:
      - 3000:3000
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=project_pa
      - MYSQL_PORT=3306
      - MYSQL_HOST=dbmysql
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password
    env_file:
      - .env
    depends_on:
      - dbmysql

  websocketserver:
    build: ./Server
    restart: on-failure
    ports:
      - 3001:3001
    environment:
      - DB_HOST=localhost
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=project_pa
      - DB_PORT=3306
      - WS_PORT=3001
      - ERROR_PERCENTAGE=15
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password
    env_file:
      - .env
    depends_on: 
      - dbmysql
      - api

  websocketclient:
    build: ./Client
    restart: on-failure
    environment:
      - DB_HOST=localhost
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=project_pa
      - DB_PORT=3306
      - WS_PORT=3001
      - ERROR_PERCENTAGE=15
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password
    env_file:
      - .env 

          
